apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: topology-hinter
  name: manager-metrics-service
  namespace: topology-hinter
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: topology-hinter
