# permissions for end users to edit endpointslices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpointslice-editor-role
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: 
  - discovery.k8s.io
  resources:
  - endpointslices/status
  verbs:
  - get
