# permissions for end users to edit endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoints-editor-role
rules:
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups: [""]
  resources:
  - endpoints/status
  verbs:
  - get
- apiGroups: [""]
  resources:
  - endpoints/finalizers
  verbs:
  - update