# permissions for end users to view service.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-viewer-role
rules:
- apiGroups: [""]
  resources:
  - services
  verbs:
  - get
  - list
  - watch
